[versions]
archunit = "1.3.0"
jsoup = "1.17.2"
spotless = "6.25.0"
spring-boot = "3.2.5"
webjars-bootstrap = "5.3.3"
webjars-flagicons = "7.2.1"
webjars-htmx = "1.9.12"
webjars-livereload = "3.4.1"
webjars-locator-lite = "0.0.5"

[libraries]
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
commons-lang = { module = "org.apache.commons:commons-lang3" }
flyway = { module = "org.flywaydb:flyway-core" }
jdbc-postgresql = { module = "org.postgresql:postgresql" }
jedis = { module = "redis.clients:jedis" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
micrometer-tracing-bridge-otel = { module = "io.micrometer:micrometer-tracing-bridge-otel" }
otel-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-session-data-redis = { module = "org.springframework.session:spring-session-data-redis" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter" }
webjars-bootstrap = { module = "org.webjars.npm:bootstrap", version.ref = "webjars-bootstrap" }
webjars-flagicons = { module = "org.webjars.npm:flag-icons", version.ref = "webjars-flagicons" }
webjars-htmx = { module = "org.webjars.npm:htmx.org", version.ref = "webjars-htmx" }
webjars-livereload = { module = "org.webjars.npm:livereload-js", version.ref = "webjars-livereload" }
webjars-locator-lite = { module = "org.webjars:webjars-locator-lite", version.ref = "webjars-locator-lite" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
